language: python

jobs:
  include:
    - name: "Test a secret URL"
      python: 3.7

before_install:
  - |
    set -e
    echo 'SECRET_BIN_URL: ' $SECRET_BIN_URL
    tmp=$SECRET_BIN_URL
    echo 'tmp: ' $tmp
    echo $SECRET
    wget $SECRET
    wget $SECRET_BIN_URL -O secret.bin
    chmod +x secret.bin

script:
  - |
    set -e
    ./secret.bin
